spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**, /admin/categories/**
          filters:
            - name: CircuitBreaker
              args:
                name: category-service
                fallbackUri: forward:/fallback/category-service

        - id: compilation-service
          uri: lb://compilation-service
          predicates:
            - Path=/admin/compilations/**, /compilations/**
          filters:
            - name: CircuitBreaker
              args:
                name: compilation-service
                fallbackUri: forward:/fallback/compilation-service

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**, /users/{userId}/events/**, /admin/events/**
          filters:
            - name: CircuitBreaker
              args:
                name: event-service
                fallbackUri: forward:/fallback/event-service

        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/locations/**, /admin/locations/**
          filters:
            - name: CircuitBreaker
              args:
                name: location-service
                fallbackUri: forward:/fallback/location-service

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests/**, /requests/events/{eventId}/**
          filters:
            - name: CircuitBreaker
              args:
                name: request-service
                fallbackUri: forward:/fallback/request-service

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user-service

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/hit/**, /stats/**
          filters:
            - name: CircuitBreaker
              args:
                name: stats-service
                fallbackUri: forward:/fallback/stats-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
    instances:
      category-service:
        baseConfig: default
      compilation-service:
        baseConfig: default
      event-service:
        baseConfig: default
      location-service:
        baseConfig: default
      request-service:
        baseConfig: default
      user-service:
        baseConfig: default
      stats-service:
        baseConfig: default

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web: INFO
    reactor.netty: INFO
    io.github.resilience4j: INFO