server:
  port: 8080

spring:
  application:
    name: main-service
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm-main
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    discovery:
      enabled: true

stats-server:
  url: http://stats-server:9090
  hit: "/hit"
  stats: "/stats"

management:
  endpoints:
    web:
      exposure:
        include: health,info