spring:
  application:
    name: stats-server
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
        max-interval: 10000
    loadbalancer:
      cache:
        enabled: false
    service-registry:
      auto-registration:
        enabled: true
        fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30