server:
  port: 8086

spring:
  application:
    name: user-service
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:postgresql://user-db:5432/user-db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      cache:
        enabled: false
      retry:
        enabled: true
        retry-on-all-operations: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      eventService:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        retryExceptions:
          - java.net.UnknownHostException
          - feign.RetryableException
    instances:
      eventService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    circuitbreakers:
      enabled: true