spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
        max-interval: 6000
        multiplier: 1.5

eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20