spring:
  application:
    name: analyzer
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      properties:
        schema.registry.url: http://schema-registry:9102
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  cloud:
    loadbalancer:
      retry:
        enabled: true
        retry-on-all-operations: true
      service-discovery:
        timeout: 1s

server:
  port: 0

collector:
  topic:
    stats:
      user-actions:
        v1: stats.user-actions.v1

grpc:
  server:
    port: ${COLLECTOR_GRPC_PORT:0}

resilience4j.circuitbreaker:
  instances:
    myService:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true