server:
  port: 9090

spring:
  application:
    name: stats-server
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:h2:mem:/stats
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info