server:
  port: 9090

spring:
  application:
    name: stats-server
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:postgresql://stats-db:5432/ewm-stats
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info