spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2   # Интервал первой регистрации

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5  # Частота обновления аренды
    lease-expiration-duration-in-seconds: 20 # Время истечения аренды

